// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNTBfNTQyQW9zZ3QUHeI2nBnDRGpI1AM',
    appId: '1:696837226113:web:00beceefc0ccb4b8201780',
    messagingSenderId: '696837226113',
    projectId: 'ecobuzz-app-e5459',
    authDomain: 'ecobuzz-app-e5459.firebaseapp.com',
    storageBucket: 'ecobuzz-app-e5459.firebasestorage.app',
    measurementId: 'G-K2ERS4DBRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGratif_3DUqabpbNq3iruneH7PGSOT9w',
    appId: '1:696837226113:android:12a7c259542538db201780',
    messagingSenderId: '696837226113',
    projectId: 'ecobuzz-app-e5459',
    storageBucket: 'ecobuzz-app-e5459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1cy9GqQCJmP6PL9Y6PdCxKpfbfQMM-I',
    appId: '1:696837226113:ios:7ef8de713a93f8ea201780',
    messagingSenderId: '696837226113',
    projectId: 'ecobuzz-app-e5459',
    storageBucket: 'ecobuzz-app-e5459.firebasestorage.app',
    iosBundleId: 'br.com.ecobuzz.ecobuzz',
  );
}
